//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BearShopEntities : DbContext
    {
        public BearShopEntities()
            : base("name=BearShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AdminMenu> AdminMenus { get; set; }
        public virtual DbSet<AdvImag> AdvImags { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ChuyenCuaGau> ChuyenCuaGaus { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Footer> Footers { get; set; }
        public virtual DbSet<GroupCusUser> GroupCusUsers { get; set; }
        public virtual DbSet<Header> Headers { get; set; }
        public virtual DbSet<HomeMenu> HomeMenus { get; set; }
        public virtual DbSet<InfoUseful> InfoUsefuls { get; set; }
        public virtual DbSet<Instruction> Instructions { get; set; }
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<tbl_CountAccess> tbl_CountAccess { get; set; }
        public virtual DbSet<tbl_FeedBack> tbl_FeedBack { get; set; }
        public virtual DbSet<tbl_GalleryCategory> tbl_GalleryCategory { get; set; }
        public virtual DbSet<tbl_GroupUser> tbl_GroupUser { get; set; }
        public virtual DbSet<tbl_Logs> tbl_Logs { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_SlideImages> tbl_SlideImages { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAdmin> UserAdmins { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
